[package]
name = "cat-mysql"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "mysql" ] }
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"