apiVersion: "fluvio.infinyon.com/v1"
kind: SpuGroup
metadata:
  name: "group1"
spec:
  replicas: 1
  minId: 10
  template:
    spec:
      env:
        - name: "RUST_LOG"
          value: "spu_server=debug"
